**IMPORT LIBRARY PENDUKUNG**

In [43]:
import trafilatura
import pandas as pd
from lxml import html

**Halaman utama artikel Sport (Bulutangkis)**

In [35]:
url = "https://sport.detik.com/raket"

downloaded = trafilatura.fetch_url(url)
tree = html.fromstring(downloaded)

links = tree.xpath('//a/@href')

**Ambil URL artikel**

In [36]:
article_links = []

for link in links:
    if "/raket/d-" in link:
        article_links.append(link)

**Hilangkan Link Duplikat**

In [37]:
all_article_links = list(dict.fromkeys(article_links))

print("Dari halaman utama:", len(all_article_links))

Dari halaman utama: 51

**Ambil dari halaman indeks 1 sampai mendapatkan 100 artikel**

In [38]:
for page in range(1, 157):

    if len(all_article_links) >= 100:
        break

    url_index = f"https://sport.detik.com/raket/indeks?page={page}"

    downloaded = trafilatura.fetch_url(url_index)

    if downloaded is None:
        continue

    tree = html.fromstring(downloaded)
    links = tree.xpath('//a/@href')

    for link in links:
        if "/raket/d-" in link and link not in all_article_links:
            all_article_links.append(link)

    print("Page", page, "-> total:", len(all_article_links))

Page 1 -> total: 51
Page 2 -> total: 51
Page 3 -> total: 60
Page 4 -> total: 80
Page 5 -> total: 100

**Hasil**

In [40]:
sport_links = all_article_links[:100]

print("total berita sport:", len(sport_links))

total berita sport: 100

**Mengambil Isi dari 100 artikel sport raket**

In [41]:
import time

sport_data = []

for i, url in enumerate(sport_links, start=1):
    try:
        downloaded = trafilatura.fetch_url(url)
        if downloaded:
            text = trafilatura.extract(downloaded)
            if text:
                sport_data.append({
                    "ID": i,
                    "Isi berita": text,
                    "label": "Sport"
                })
        print(f"{i}/100 selesai")
        time.sleep(1)
    except Exception as e:
        print(f"{i}/100 gagal: {e}")

print("Jumlah berita berhasil:", len(sport_data))

1/100 selesai
2/100 selesai
3/100 selesai
4/100 selesai
5/100 selesai
6/100 selesai
7/100 selesai
8/100 selesai
9/100 selesai
10/100 selesai
11/100 selesai
12/100 selesai
13/100 selesai
14/100 selesai
15/100 selesai
16/100 selesai
17/100 selesai
18/100 selesai
19/100 selesai
20/100 selesai
21/100 selesai
22/100 selesai
23/100 selesai
24/100 selesai
25/100 selesai
26/100 selesai
27/100 selesai
28/100 selesai
29/100 selesai
30/100 selesai
31/100 selesai
32/100 selesai
33/100 selesai
34/100 selesai
35/100 selesai
36/100 selesai
37/100 selesai
38/100 selesai
39/100 selesai
40/100 selesai
41/100 selesai
42/100 selesai
43/100 selesai
44/100 selesai
45/100 selesai
46/100 selesai
47/100 selesai
48/100 selesai
49/100 selesai
50/100 selesai
51/100 selesai
52/100 selesai
53/100 selesai
54/100 selesai
55/100 selesai
56/100 selesai
57/100 selesai
58/100 selesai
59/100 selesai
60/100 selesai
61/100 selesai
62/100 selesai
63/100 selesai
64/100 selesai
65/100 selesai
66/100 selesai
67/100 selesai
68/100 selesai
69/100 selesai
70/100 selesai
71/100 selesai
72/100 selesai
73/100 selesai
74/100 selesai
75/100 selesai
76/100 selesai
77/100 selesai
78/100 selesai
79/100 selesai
80/100 selesai
81/100 selesai
82/100 selesai
83/100 selesai
84/100 selesai
85/100 selesai
86/100 selesai
87/100 selesai
88/100 selesai
89/100 selesai
90/100 selesai
91/100 selesai
92/100 selesai
93/100 selesai
94/100 selesai
95/100 selesai
96/100 selesai
97/100 selesai
98/100 selesai
99/100 selesai
100/100 selesai
Jumlah berita berhasil: 100

**Menampilkan Hasil Scraping topik sport**

In [44]:
df_sport = pd.DataFrame(sport_data)

df_sport.head()

   ID                                         Isi berita  label
0   1  Persatuan Bulutangkis Indonesia (PBSI) baru sa...  Sport
1   2  Tunggal putra Indonesia, Jonatan Christie, men...  Sport
2   3  Sabar Karyaman Gutama/Moh Reza Pahlevi Isfahan...  Sport
3   4  Dua petenis Indonesia menyusul Nathan Barki lo...  Sport
4   5  Babak utama Seri IV M-15 Men's World Tennis Ch...  Sport

## Scraping topik Finance

In [54]:
# Mulai dari halaman utama Finance
url = "https://finance.detik.com/finansial"

downloaded = trafilatura.fetch_url(url)
tree = html.fromstring(downloaded)
links = tree.xpath('//a/@href')

finance_article_links = []

for link in links:
    if link.startswith("https://finance.detik.com/") and "/d-" in link:
        if link not in finance_article_links:
            finance_article_links.append(link)

print("Dari halaman utama:", len(finance_article_links))


# Tambahkan dari halaman indeks
for page in range(1, 20):

    if len(finance_article_links) >= 100:
        break

    url_index = f"https://finance.detik.com/indeks?page={page}"

    downloaded = trafilatura.fetch_url(url_index)

    if downloaded is None:
        continue

    tree = html.fromstring(downloaded)
    links = tree.xpath('//a/@href')

    for link in links:
        if link.startswith("https://finance.detik.com/") and "/d-" in link:
            if link not in finance_article_links:
                finance_article_links.append(link)

    print("Page", page, "-> total:", len(finance_article_links))


# Ambil tepat 100 artikel
finance_links = finance_article_links[:100]

print()
print("================================")
print("TOTAL BERITA FINANCE:", len(finance_links))
print("================================")

Dari halaman utama: 70
Page 1 -> total: 87
Page 2 -> total: 96
Page 3 -> total: 108

================================
TOTAL BERITA FINANCE: 100
================================

In [55]:
import time

finance_data = []

for i, url in enumerate(finance_links, start=101):
    try:
        downloaded = trafilatura.fetch_url(url)

        if downloaded:
            text = trafilatura.extract(downloaded)

            if text:
                finance_data.append({
                    "ID": i,
                    "Isi berita": text,
                    "label": "Finance"
                })

        print(f"{i}/200 selesai")

        time.sleep(1)

    except Exception as e:
        print(f"{i}/200 gagal: {e}")

print()
print("Jumlah berita Finance berhasil:", len(finance_data))

101/200 selesai
102/200 selesai
103/200 selesai
104/200 selesai
105/200 selesai
106/200 selesai
107/200 selesai
108/200 selesai
109/200 selesai
110/200 selesai
111/200 selesai
112/200 selesai
113/200 selesai
114/200 selesai
115/200 selesai
116/200 selesai
117/200 selesai
118/200 selesai
119/200 selesai
120/200 selesai
121/200 selesai
122/200 selesai
123/200 selesai
124/200 selesai
125/200 selesai
126/200 selesai
127/200 selesai
128/200 selesai
129/200 selesai
130/200 selesai
131/200 selesai
132/200 selesai
133/200 selesai
134/200 selesai
135/200 selesai
136/200 selesai
137/200 selesai
138/200 selesai
139/200 selesai
140/200 selesai
141/200 selesai
142/200 selesai
143/200 selesai
144/200 selesai
145/200 selesai
146/200 selesai
147/200 selesai
148/200 selesai
149/200 selesai
150/200 selesai
151/200 selesai
152/200 selesai
153/200 selesai
154/200 selesai
155/200 selesai
156/200 selesai
157/200 selesai
158/200 selesai
159/200 selesai
160/200 selesai
161/200 selesai
162/200 selesai
163/200 selesai
164/200 selesai
165/200 selesai
166/200 selesai
167/200 selesai
168/200 selesai
169/200 selesai
170/200 selesai
171/200 selesai
172/200 selesai
173/200 selesai
174/200 selesai
175/200 selesai
176/200 selesai
177/200 selesai
178/200 selesai
179/200 selesai
180/200 selesai
181/200 selesai
182/200 selesai
183/200 selesai
184/200 selesai
185/200 selesai
186/200 selesai
187/200 selesai
188/200 selesai
189/200 selesai
190/200 selesai
191/200 selesai
192/200 selesai
193/200 selesai
194/200 selesai
195/200 selesai
196/200 selesai
197/200 selesai
198/200 selesai
199/200 selesai
200/200 selesai

Jumlah berita Finance berhasil: 100

In [56]:
df_finance = pd.DataFrame(finance_data)

df_finance.head()

    ID                                         Isi berita    label
0  101  Indeks Harga Saham Gabungan (IHSG) ditutup men...  Finance
1  102  Market Overview\nIndeks Harga Saham Gabungan (...  Finance
2  103  Indeks Harga Saham Gabungan (IHSG) pagi ini di...  Finance
3  104  Otoritas Jasa Keuangan (OJK) mengusulkan perub...  Finance
4  105  Sebanyak 13 Bank Perekonomian Rakyat (BPR) dan...  Finance

In [58]:
df_final = pd.concat([df_sport, df_finance], ignore_index=True)


df_final.head()
print("Jumlah data:", len(df_final))

Jumlah data: 200